version: "3.9"

services:
  backend:
    build: .
    container_name: pdf-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./core:/app/core            # mount your offline core logic
      - ./app:/app/app              # mount API code
      - ./sample_dataset:/app/sample_dataset
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

